### ISSUE TITLE
cannot find suitable PyQt installation

### ISSUE THREAD

**Issue by triccare** [aroberge/easygui_qt#19]
Either installing from the repo clone using

    python setup.py install

or

    pip install easygui_qt

I get the error

    Could not find suitable distribution for Requirement.parse('PyQt4')

PyQt4 is install and importable. This is with python 2.7.9 under OSX 10.8.5

**Comment by aroberge** [comment]
Fixed with version 0.9.1 - my apologies about this. 

Please note that I am in the middle of changing the naming convention of a few widgets and the documentation may not completely reflect the name in the package.  In particular, show_message() has yet to be renamed to show().  Using dir() and help() at the Python prompt is a more fool-proof way to get information than consulting the online documentation.

**Comment by triccare** [comment]
thanks for the update and the heads-up on the documentation. Usually prefer source over docs anyways.
